yiisoft/yii2-authclient

Collection.php
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
I remove GoogleOpenId class in `yii\authclient\Collection` example, Also change in your official docs http://www.yiiframework.com/doc-2.0/yii-authclient-collection.html.
Because this auth method is no longer supported by Google as of April 20, 2015 and also you are deprecated since version 2.0.4.
=> Update example in comments.

CHANGELOG.md, clients/Facebook.php
=> Fix #163: Added support for access token exchange and client-specific access tokens at `Facebook`

CHANGELOG.md, src/signature/RsaSha.php
This addresses issue #211
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | #211
=> Missing $key in openssl_pkey_get_private()

CHANGELOG.md, src/OAuth2.php
…g #241
| Fixed issues  | #241
=> Unset parameter `scope` on `defaultReturnUrl` for `OAuth2`, fixing bug #241

CHANGELOG.md, src/AuthAction.php
| Fixed issues  | 
I often want to use a custom state token, because I need to access data after the successful authentication. That's why I put a payload into my custom state token.
Now, I need to duplicate the complete `authOAuth2` method to inject my custom state token into the auth url.
This PR allows to pass the `$params` attribute to `buildAuthUrl()` method without duplicating the complete `authOAuth2` method, but overriding only the `run()` method.
=> allow to pass buildAuthUrl params to OAuth flows

CHANGELOG.md, src/clients/Google.php
| Breaks BC?    | yes
| Fixed issues  | #258 
It breaks backward compatibility because `initUserAttributes` now returns different set of attributes. But since it will stop working anyway (because G+ is deprecated) it is not such a big issue. End-user code that uses `yii\authclient\clients\Google` need to be rewritten anyway
=> Use oauth2 Google API endpoint instead of plus

CHANGELOG.md, src/OpenIdConnect.php
=> Fixes #273: `OpenIdConnect::validateClaims()` is now protected

CHANGELOG.md, src/BaseOAuth.php, src/OAuth1.php, src/OAuth2.php, src/OpenIdConnect.php, tests/BaseOAuthTest.php, tests/clients/GoogleHybridTest.php, tests/clients/GoogleTest.php, tests/traits/OAuthDefaultReturnUrlTestTrait.php
| Tests pass?   | yes/no
| Fixed issues  | #274, #245, #244 
Since this is the second time (to me), when production Google login stops working, then I twisted a bit on the default return url generation.
Instead of removing every unnecessary url parameters, I think we should allow to configure which parameters what we should keep in the url. This way is future proof, if new parameters appears in the url.
=> allow to set OAuth2 parameters to keep in default return url

composer.json, docs/guide-ja/open-id-connect.md, docs/guide/open-id-connect.md, src/OpenIdConnect.php
| Fixed issues  | 
Related to PR #285 there was a missing composer suggested dependency in `composer.json` and in the documentation and the version requirement was not accurate we can use version 1.x (compatible for php >= 7.1) or 2.x (compatible for php >= 7.3). Sorry for that I've should have seen it before.
=> Fix missing information in documentation

CHANGELOG.md, src/CacheStateStorage.php
| Fixed issues  | #205 
I'm also using the cache state storage, I don't think it fixed the issue #205 but I think it can be a good add-on and reply to some use case (mine is using the authclient in CLI where session is not available) so instead of having each one our own implementation, I think it make more sense to have it directly in the extension, what do you think ?
=> Add aleternative statestorage in cache

CHANGELOG.md, src/BaseOAuth.php, tests/traits/OAuthDefaultReturnUrlTestTrait.php
=> Fix #309 `BaseOAuth->beforeApiRequestSend()` try to refresh token if `BaseOAuth->autoRefreshAccessToken = true`

CHANGELOG.md, src/BaseOAuth.php
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
This method is used to send requests. But after receiving a response, they did not initial `InvalidResponseException `in the right way. It is missed the statusCode from the response that we need it to pass into `InvalidResponseException`, `yii\base\Exception` and `\Exception`
That's why the method `getCode()` from `\Exception` is always zero.
=> Fix method getCode is always zero in php Exception

CHANGELOG.md, composer.json, src/OAuth1.php, tests/TokenTest.php
| Fixed issues  | related to https://github.com/yiisoft/yii2/pull/18817
=> Use `random_int()` when generating OAuth1 nonce

CHANGELOG.md, src/OpenIdConnect.php, tests/OpenIdConnectTest.php
According to https://openid.net/specs/openid-connect-discovery-1_0.html#rfc.section.3 the `token_endpoint_auth_methods_supported` is optional. This PR makes sure the OpenID Connect client uses the default value of `'client_secret_basic'` in case it isn't specified.
=> OpenID Connect `token_endpoint_auth_methods_supported` is optional

CHANGELOG.md, src/OpenIdConnect.php
This PR resolves a bug when using `\yii\authclient\OpenIdConnect::refreshAccessToken()` when `\yii\authclient\OpenIdConnect::getValidateAuthNonce()` is `true` caused by the 'nonce' not being present in the 'state'. It also prevents re-using of the `nonce` from the original `$authCode` by creating a new one instead of using the existing one.
=> Regenerate `nonce` when refreshing access token with OpenId Connect

CHANGELOG.md, src/OpenIdConnect.php, tests/OpenIdConnectTest.php
| New feature?  | ✔️
| Fixed issues  | #240
=> Use `id_token` claim for getUserAttributes() if 'userinfo_endpoint' is not available.

CHANGELOG.md, src/BaseOAuth.php, src/OpenIdConnect.php, tests/OpenIdConnectTest.php
| New feature?  | ✔️
Some server can return a JWT in the Userinfo Response:
https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse
> If the UserInfo Response is signed and/or encrypted, then the Claims are returned in a JWT and the content-type MUST be `application/jwt`
=> Support JWT in userinfo_endpoint response for OpenID Connect

CHANGELOG.md, src/BaseOAuth.php
Facebook is throwing 400 Error when userAgent has latin characters (e.g. "ż").
| Fix issue   | #345
=> Facebook OAuth 400 error when latin characters are used in App name

docs/guide/open-id-connect.md
jwt-key-mgmt exists in the json example but is missing for the cli example
| New feature?  |❌
| Breaks BC?    |❌
| Fixed issues  |
=> Add jwt-key-mgmt to the composer require cli example

docs/guide/open-id-connect.md
`web-token/jwt-key-mgmt` package vendor name is missing in the composer require cli example.
| Fixed issues  |
=> Fix jwt-key-mgmt package name in the composer require cli example

CHANGELOG.md, src/OAuth2.php
=> Fixes #351: Unable to set TokenParamKey in OAuth2 config, gets hard overwritten in OAuth2::createToken()

CHANGELOG.md, src/BaseOAuth.php, src/ClientErrorResponseException.php, src/InvalidResponseException.php, src/clients/VKontakte.php, tests/BaseOAuthTest.php, tests/OpenIdConnectTest.php
| New feature?  | ✔️
This PR allows to filter out client error response codes (4xx). E.g.
```php
try {
$client->api('https://test');
} catch (ClientErrorResponseException $e) {
// Handle client error response
}
```
=> Added ClientErrorResponseException for 4xx response codes

CHANGELOG.md, src/OpenIdConnect.php
| Breaks BC?    | ✔️
| Fixed issues  | #364 
Instead of using the issuer URL from $this->issueUrl, we now get it from the openid configuration.
=> fix: use issuer URL from openid configuration

CHANGELOG.md, src/Collection.php
The [deprecated exception](https://github.com/yiisoft/yii2/blob/master/framework/base/InvalidParamException.php#L16) has been replaced with the appropriate one, ensuring backward compatibility since the [new exception derives from the old one](https://github.com/yiisoft/yii2/blob/master/framework/base/InvalidArgumentException.php#L17).
=> Fix deprecated exception in collection component

CHANGELOG.md, src/OAuth2.php, src/OpenIdConnect.php, src/clients/GitHub.php, src/clients/Oauth2Client.php, src/clients/TwitterOAuth2.php, tests/clients/FacebookTest.php, tests/clients/GitHubTest.php, tests/clients/GoogleHybridTest.php, tests/clients/GoogleTest.php, tests/clients/LinkedInTest.php, tests/clients/LiveTest.php, tests/clients/Oauth2ClientTest.php, tests/clients/OpenIdConnectTest.php, tests/clients/TwitterOAuth2Test.php, tests/clients/VKontakteTest.php, tests/clients/YandexTest.php, tests/clients/base/BaseOauth2ClientTestCase.php
| New feature?  | ✔️
| Fixed issues  | #386
This PR adds support for easy configuration of the location of the access token in API requests for Oauth 2 clients.
It also adds a "plain" oauth 2 client that uses the access token in the header by default as specified in [RFC6749#section-7](https://datatracker.ietf.org/doc/html/rfc6749#section-7).
=> Added support to configure the Oauth2 access token location in requests

CHANGELOG.md, src/OpenIdConnect.php
=> Add OpenIdConnect cache duration configuration option

CHANGELOG.md, src/OpenIdConnect.php
| Fixed issues  | #391
Using array as default value for `token_endpoint_auth_methods_supported` in `\yii\authclient\OpenIdConnect::applyClientCredentialsToRequest()`
=> Fix #392: Now using array as default value for `token_endpoint_auth_methods_supported` in `OpenIdConnect::applyClientCredentialsToRequest()`

CHANGELOG.md, src/BaseOAuth.php, src/OpenIdConnect.php
| Fixed issues  | 
The access token can be null, but only OAuthToken is specified in the type. Such a situation can definitely happen and it is even checked by tests.
In my project, I bypassed this, but I would like to fix the type in the source code.
=> Fix type for BaseOAuth property - accessToken

docs/guide-ja/oauth-direct-authentication.md, docs/guide-ja/quick-start.md, docs/guide-ja/usage-api.md, docs/guide-ru/oauth-direct-authentication.md, docs/guide-ru/quick-start.md, docs/guide-ru/usage-api.md, docs/guide-zh-CN/quick-start.md, docs/guide/oauth-direct-authentication.md, docs/guide/quick-start.md, docs/guide/usage-api.md, src/AuthAction.php, src/views/redirect.php, src/widgets/AuthChoice.php, tests/CollectionTest.php, tests/OAuth1Test.php
| Fixed issues  | 
https://docs.phpdoc.org/guide/references/phpdoc/tags/var.html
=> Fix @var tags syntax

CHANGELOG.md, src/clients/VKontakte.php
VK changed their api domain and subdomains from vk.com to vk.ru
References: [vk official changelog 2.6.1 (10-09-2025)]( https://id.vk.com/about/business/go/docs/en/vkid/latest/vk-id/release-notes#Izmeneniya-Web-VK-ID-SDK).
=> Change vk.com domain to vk.ru domain
