- docs/guide/installation.md
Added apostrophe for correct work of phpmyadmin
> Fixed query for phpmyadmin

- docs/guide-ja/installation.md
- docs/guide-ja/quick-start.md
> docs/guide-ja updated [skip ci]

- Collection.php
| Tests pass?   | no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
Sorry, I have forgot start(*) in #115 pull request. Its display red background.
> Pull request #115 Forgot start(*) in stating line. Its incorrect.

- BaseClient.php
- BaseOAuth.php
- CHANGELOG.md
- SessionStateStorage.php
- StateStorageInterface.php
- tests/BaseClientTest.php
- tests/SessionStateStorageTest.php
- tests/data/Session.php
> Auth client 'State Storage' abstraction layer extracted

- docs/guide-ja/README.md
- docs/guide-ja/oauth-direct-authentication.md
- docs/guide-ja/quick-start.md
- docs/guide-ja/setup-http-client.md
- docs/guide-ja/usage-api.md
Japanese documentation updated
> Japanese documentation updated [ci skip]

- CHANGELOG.md
- widgets/AuthChoice.php
> Use noConflict jQuery with widget

- CHANGELOG.md
- OAuth1.php
- OAuth2.php
- OpenIdConnect.php
- composer.json
- tests/OpenIdConnectTest.php
- widgets/AuthChoice.php
> Fix #155 Add OpenIDConnect

- docs/guide-ja/open-id-connect.md
- docs/guide-ja/third-party-auth-clients.md
| Is bugfix?    | yes (doc encoding fix)
| Tests pass?   | --
| Fixed issues  | --
> docs encoding fixed [ci skip]

- CHANGELOG.md
- src/clients/VKontakte.php
| Breaks BC?    | yes/no
| Fixed issues  |  #198
> fix vk auth

- docs/guide-ja/third-party-auth-clients.md
- docs/guide/third-party-auth-clients.md
| Is bugfix?    | no (doc)
| Breaks BC?    | yes
| Fixed issues  |
> add spotify and gitlab client

- CHANGELOG.md
- docs/guide/quick-start.md
- src/OpenIdConnect.php
| Breaks BC?    | unsure
| Fixed issues  | #220
> Fix OpenIdConnect provider call to UserInfo yiisoft/yii2-authclient#220

- CHANGELOG.md
- src/AuthAction.php
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
> fix cancel redirect from linkedIn

- CHANGELOG.md
- src/clients/VKontakte.php
| Fixed issues  | #276 
Hello, this PR based on #276 our discussion about VK developers recommendations
> Bump vk default API version

- .travis.yml
- docs/guide-ja/third-party-auth-clients.md
- docs/guide-ru/third-party-auth-clients.md
- docs/guide/third-party-auth-clients.md
This PR adds references to a new third party auth client that follow OIDC standard and comes as an yii2 authclient extension.
> Add third party extension oidc

- CHANGELOG.md
- composer.json
- docs/guide-ja/open-id-connect.md
- docs/guide/open-id-connect.md
- src/OpenIdConnect.php
> Replace JOSE library by JWT Framework

- CHANGELOG.md
- UPGRADE.md
- src/BaseClient.php
| Is bugfix?    | kind of
| Breaks BC?    | it depends
| Tests pass?   | ?
> Default request option for turning off SSL peer verification was removed

- README.md
> Update README.md for the latest version

- CHANGELOG.md
- src/BaseOAuth.php
| Fixed issues  | #310
I think this would be the correct check to refresh access tokens.
> do not refresh access token if it is not expired

- CHANGELOG.md
- src/OAuth2.php
- tests/OAuth2Test.php
| Tests pass?   | ?
| Fixed issues  | N/A
I was using a OpenID Connect integration that required PKCE. This is the fixes Is this a PR you are willing to accept with a bit of cean up / testing
> feat: add pkce support

- docs/guide/quick-start.md
Fix #321
| Tests pass?   | -
| Fixed issues  | #321
> Fix #321 - add note for GitHub client callback URL

- CHANGELOG.md
- src/OpenIdConnect.php
> OIDC: 'aud' claims can be arrays

- CHANGELOG.md
- src/OpenIdConnect.php
- tests/OpenIdConnectTest.php
> Use nonce from the authentication request

- docs/guide/installation.md
- docs/guide/oauth-direct-authentication.md
- docs/guide/quick-start.md
> Typo fixes

- src/BaseOAuth.php
> Fixed BaseOAuth api docblock

- CHANGELOG.md
- src/AuthAction.php
- tests/AuthActionTest.php
> Add property defaultClientId to AuthAction

- composer.json
- tests/OpenIdConnectTest.php
- Added the `allowed-plugins` sections to composer.json
- Fixed the expected exception in `OpenIdConnectTest`
> chore(ci): Fix tests

- docs/guide-ja/README.md
- docs/guide-ja/oauth-direct-authentication.md
- docs/guide-ja/open-id-connect.md
- docs/guide-ru/README.md
- docs/guide-zh-CN/README.md
- docs/guide/README.md
- docs/guide/open-id-connect.md
| Fixed issues  | resolve https://github.com/yiisoft/yii2-authclient/issues/371
> update docs folder links

- src/BaseOAuth.php
- src/OAuth2.php
- src/OpenId.php
- src/OpenIdConnect.php
- src/assets/authchoice.js
- src/clients/Facebook.php
- src/clients/GitHub.php
- src/clients/Live.php
- src/clients/VKontakte.php
- src/clients/Yandex.php
- src/signature/HmacSha.php
- src/signature/RsaSha.php
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/yii2-authclient/issues/373
> update src folder links

- CHANGELOG.md
- README.md
- composer.json
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/yii2-authclient/issues/375
> update root folder links
